# Form implementation generated from reading ui file 'ui/manual_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_manual_window(object):
    def setupUi(self, manual_window):
        manual_window.setObjectName("manual_window")
        manual_window.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        manual_window.resize(633, 483)
        manual_window.setMinimumSize(QtCore.QSize(633, 483))
        manual_window.setMaximumSize(QtCore.QSize(633, 483))
        self.ok_btn = QtWidgets.QPushButton(manual_window)
        self.ok_btn.setGeometry(QtCore.QRect(270, 450, 80, 25))
        self.ok_btn.setChecked(False)
        self.ok_btn.setObjectName("ok_btn")
        self.manual_text = QtWidgets.QTextBrowser(manual_window)
        self.manual_text.setGeometry(QtCore.QRect(4, 10, 621, 431))
        self.manual_text.setObjectName("manual_text")

        self.retranslateUi(manual_window)
        QtCore.QMetaObject.connectSlotsByName(manual_window)

    def retranslateUi(self, manual_window):
        _translate = QtCore.QCoreApplication.translate
        manual_window.setWindowTitle(_translate("manual_window", "Инструкция"))
        self.ok_btn.setText(_translate("manual_window", "Ок"))
        self.manual_text.setHtml(_translate("manual_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Полученные данные записываются в файл для записи: &quot;</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">готовый файл.xlsm</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;. При отсутствии данного файла в момент запуска парсера он будет создан автоматически. Все остальные файлы не обязательны к наличию — будут пропущены. Названия файлов и папок не привязаны к регистру. Файлы для парсинга не привязаны ни к регистру, ни к расширению.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">После завершения работы программы окно закроется автоматически через время установленное в настройках.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Для расширения определения гендера можно заносить дополнительные имена в соответствующие текстовые файлы (</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">с большой буквы(!)</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">, через запятую/пробел/перенесение строки).</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Парсер работает по всем Excel файлам, находящимся в папках, соответствующих названиям компаний:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Альфа</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Альянс</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Ингосстрах</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Ренессанс</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Ресо</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Росгосстрах</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Согаз</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot; - (файлы у которых ФИО в одном столбце)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Согаз ф_и_о</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot; - (файлы у которых ФИО в разных столбцах)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Согласие 13</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot; - (файлы у которых первая запись клиента начинается на 13 строке)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot;</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">Согласие 15</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot; - (файлы у которых первая запись клиента начинается на 15 строке)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">После прочтения файла парсером прочитанный файл перемещается во вложенную папку &quot;</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:600;\">прочитанные файлы</span><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">&quot; (создается автоматически в случае отсутствия). При наличии в папке &quot;прочитанные файлы&quot; файла с таким же именем, как у перемещаемого файла, файл не будет перемещен.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt;\">Схема расположения файлов:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">&quot;парсер&quot;/&quot;готовый файл.xlsm&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">&quot;парсер&quot;/списки имён/&quot;мужские(женские) имена.txt&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">&quot;парсер&quot;/списки от СК/&quot;папка из списка&quot;/&quot;файлы для парсинга&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:11pt; font-style:italic;\">&quot;парсер&quot;/списки от СК/&quot;папка из списка&quot;/прочитанные файлы/&quot;прочитанные файлы&quot;</span></p></body></html>"))
