# Form implementation generated from reading ui file 'ui/settings_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_settings_window(object):
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        settings_window.resize(333, 333)
        settings_window.setMinimumSize(QtCore.QSize(333, 333))
        settings_window.setMaximumSize(QtCore.QSize(333, 333))
        self.apply_btn = QtWidgets.QPushButton(settings_window)
        self.apply_btn.setGeometry(QtCore.QRect(50, 300, 89, 25))
        self.apply_btn.setObjectName("apply_btn")
        self.settings_text = QtWidgets.QLabel(settings_window)
        self.settings_text.setGeometry(QtCore.QRect(110, 20, 111, 20))
        self.settings_text.setObjectName("settings_text")
        self.cancel_btn = QtWidgets.QPushButton(settings_window)
        self.cancel_btn.setGeometry(QtCore.QRect(190, 300, 89, 25))
        self.cancel_btn.setObjectName("cancel_btn")
        self.time_close_dbox = QtWidgets.QDoubleSpinBox(settings_window)
        self.time_close_dbox.setGeometry(QtCore.QRect(240, 190, 41, 21))
        self.time_close_dbox.setDecimals(1)
        self.time_close_dbox.setMinimum(1.0)
        self.time_close_dbox.setMaximum(10.0)
        self.time_close_dbox.setSingleStep(0.1)
        self.time_close_dbox.setObjectName("time_close_dbox")
        self.time_close_text = QtWidgets.QLabel(settings_window)
        self.time_close_text.setGeometry(QtCore.QRect(10, 190, 231, 21))
        self.time_close_text.setObjectName("time_close_text")
        self.language_combo_box = QtWidgets.QComboBox(settings_window)
        self.language_combo_box.setEnabled(False)
        self.language_combo_box.setGeometry(QtCore.QRect(130, 70, 69, 16))
        self.language_combo_box.setObjectName("language_combo_box")
        self.language_combo_box.addItem("")
        self.language_combo_box.addItem("")
        self.set_language_text = QtWidgets.QLabel(settings_window)
        self.set_language_text.setGeometry(QtCore.QRect(30, 70, 101, 16))
        self.set_language_text.setObjectName("set_language_text")

        self.retranslateUi(settings_window)
        QtCore.QMetaObject.connectSlotsByName(settings_window)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "Настройки"))
        self.apply_btn.setText(_translate("settings_window", "Применить"))
        self.settings_text.setText(_translate("settings_window", "Окно настроек"))
        self.cancel_btn.setText(_translate("settings_window", "Отмена"))
        self.time_close_text.setText(_translate("settings_window", "Закрыть окно после выполнения через, сек"))
        self.language_combo_box.setItemText(0, _translate("settings_window", "Rus"))
        self.language_combo_box.setItemText(1, _translate("settings_window", "Eng"))
        self.set_language_text.setText(_translate("settings_window", "Язык программы:"))
