# Form implementation generated from reading ui file 'ui/settings_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_settings_window(object):
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        settings_window.resize(333, 333)
        settings_window.setMinimumSize(QtCore.QSize(333, 333))
        settings_window.setMaximumSize(QtCore.QSize(333, 333))
        self.apply_btn = QtWidgets.QPushButton(settings_window)
        self.apply_btn.setGeometry(QtCore.QRect(40, 130, 89, 25))
        self.apply_btn.setObjectName("apply_btn")
        self.settings_text = QtWidgets.QLabel(settings_window)
        self.settings_text.setGeometry(QtCore.QRect(110, 20, 111, 20))
        self.settings_text.setObjectName("settings_text")
        self.cancel_btn = QtWidgets.QPushButton(settings_window)
        self.cancel_btn.setGeometry(QtCore.QRect(180, 130, 89, 25))
        self.cancel_btn.setObjectName("cancel_btn")
        self.time_close_dbox = QtWidgets.QDoubleSpinBox(settings_window)
        self.time_close_dbox.setGeometry(QtCore.QRect(190, 70, 51, 26))
        self.time_close_dbox.setDecimals(1)
        self.time_close_dbox.setMaximum(10.0)
        self.time_close_dbox.setSingleStep(0.1)
        self.time_close_dbox.setStepType(QtWidgets.QAbstractSpinBox.StepType.AdaptiveDecimalStepType)
        self.time_close_dbox.setObjectName("time_close_dbox")
        self.time_close_text = QtWidgets.QLabel(settings_window)
        self.time_close_text.setGeometry(QtCore.QRect(40, 70, 151, 21))
        self.time_close_text.setObjectName("time_close_text")

        self.retranslateUi(settings_window)
        QtCore.QMetaObject.connectSlotsByName(settings_window)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "Настройки"))
        self.apply_btn.setText(_translate("settings_window", "Применить"))
        self.settings_text.setText(_translate("settings_window", "Окно настроек"))
        self.cancel_btn.setText(_translate("settings_window", "Отмена"))
        self.time_close_text.setText(_translate("settings_window", "Закрыть окно через"))
