# Form implementation generated from reading ui file 'ui/easter_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_easter_window(object):
    def setupUi(self, easter_window):
        easter_window.setObjectName("easter_window")
        easter_window.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        easter_window.resize(200, 100)
        easter_window.setMinimumSize(QtCore.QSize(200, 100))
        easter_window.setMaximumSize(QtCore.QSize(200, 200))
        self.easter_text = QtWidgets.QLabel(easter_window)
        self.easter_text.setGeometry(QtCore.QRect(60, 20, 71, 20))
        self.easter_text.setObjectName("easter_text")
        self.ok_btn = QtWidgets.QPushButton(easter_window)
        self.ok_btn.setGeometry(QtCore.QRect(50, 60, 89, 25))
        self.ok_btn.setObjectName("ok_btn")

        self.retranslateUi(easter_window)
        QtCore.QMetaObject.connectSlotsByName(easter_window)

    def retranslateUi(self, easter_window):
        _translate = QtCore.QCoreApplication.translate
        easter_window.setWindowTitle(_translate("easter_window", "Пасхалка!"))
        self.easter_text.setText(_translate("easter_window", "Пасхалка!"))
        self.ok_btn.setText(_translate("easter_window", "Ок"))
