# Form implementation generated from reading ui file 'parser_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Parser(object):
    def setupUi(self, Parser):
        Parser.setObjectName("Parser")
        Parser.resize(327, 163)
        Parser.setMaximumSize(QtCore.QSize(800, 400))
        self.centralwidget = QtWidgets.QWidget(Parser)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_4)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.pushButton)
        Parser.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Parser)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 327, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        Parser.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Parser)
        self.statusbar.setObjectName("statusbar")
        Parser.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(Parser)
        self.action.setObjectName("action")
        self.action_2 = QtGui.QAction(Parser)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Parser)
        QtCore.QMetaObject.connectSlotsByName(Parser)

    def retranslateUi(self, Parser):
        _translate = QtCore.QCoreApplication.translate
        Parser.setWindowTitle(_translate("Parser", "MainWindow"))
        self.checkBox.setText(_translate("Parser", "move_after_reading"))
        self.checkBox_2.setText(_translate("Parser", "show_policies"))
        self.checkBox_3.setText(_translate("Parser", "show_data"))
        self.checkBox_4.setText(_translate("Parser", "save"))
        self.pushButton.setText(_translate("Parser", "Начать парсинг"))
        self.menu.setTitle(_translate("Parser", "Меню"))
        self.action.setText(_translate("Parser", "Выход"))
        self.action_2.setText(_translate("Parser", "О программе"))


if __name__ == '__main__':
    pass
